// js/app.js
// Navigation: buttons call renderPage() directly.
// Hash is written on nav so refresh restores the last tab.
// hashchange only fires on load/back-forward — not relied on for button clicks.

(function () {
  'use strict';

  var VALID_PAGES = ['home', 'schedule', 'teams', 'groups', 'bracket'];
  var GROUPS = ['A','B','C','D','E','F','G','H','I','J','K','L'];
  var schedSort = 1;
  var teamMap = {};

  /* ─── Navigation ─────────────────────────────── */

  function renderPage(page) {
    if (VALID_PAGES.indexOf(page) === -1) page = 'home';

    // Show/hide sections
    VALID_PAGES.forEach(function (p) {
      var s = document.getElementById('page-' + p);
      if (s) s.hidden = (p !== page);
    });

    // Active tab styling
    document.querySelectorAll('.nav-link').forEach(function (btn) {
      var active = btn.dataset.page === page;
      btn.classList.toggle('active', active);
      btn.setAttribute('aria-current', active ? 'page' : 'false');
    });

    // Update hash so refresh restores this tab
    // Use replaceState when available to avoid polluting history on every render
    if (history.replaceState) {
      history.replaceState(null, '', '#' + page);
    } else {
      window.location.hash = page;
    }

    // Render content
    if (page === 'home')     renderHome();
    if (page === 'schedule') renderSchedule();
    if (page === 'teams')    renderTeams();
    if (page === 'groups')   renderGroups();
    if (page === 'bracket')  renderBracket();

    window.scrollTo(0, 0);
  }

  function goTo(page, teamId) {
    if (teamId) {
      var tm = teamMap[teamId];
      if (tm) document.getElementById('sched-search').value = tm.name;
    }
    renderPage(page);
  }

  // Read hash on load / back-forward
  function pageFromHash() {
    var h = window.location.hash.replace('#', '');
    return VALID_PAGES.indexOf(h) !== -1 ? h : 'home';
  }

  window.addEventListener('hashchange', function () {
    renderPage(pageFromHash());
  });

  // Expose for inline handlers generated by renderTeams / renderGroups
  window.openTeamCalendar = function (teamId) { goTo('schedule', teamId); };

  /* ─── Home ───────────────────────────────────── */

  function renderHome() {
    var now = Date.now();
    var upcoming = Utils.sortByDate(MATCHES, true).filter(function (m) {
      return new Date(m.date) >= now;
    }).slice(0, 6);
    var el = document.getElementById('home-matches');
    el.innerHTML = upcoming.length
      ? upcoming.map(function (m) { return MatchCard.render(m, teamMap); }).join('')
      : emptyState('📅', 'Tournament complete. All matches played.');
  }

  /* ─── Schedule ───────────────────────────────── */

  function renderSchedule() {
    var q     = document.getElementById('sched-search').value.trim();
    var group = document.getElementById('sched-group').value;
    var stage = document.getElementById('sched-stage').value;
    var ms    = Utils.filterMatches(MATCHES, {q: q, group: group, stage: stage}, teamMap);
    ms = Utils.sortByDate(ms, schedSort === 1);
    document.getElementById('sort-date-btn').textContent = schedSort === 1 ? '↑ Date' : '↓ Date';
    var el = document.getElementById('schedule-list');
    el.innerHTML = ms.length
      ? ms.map(function (m) { return MatchCard.render(m, teamMap); }).join('')
      : emptyState('🔍', 'No matches found. Try adjusting your filters.');
  }

  function toggleDateSort() { schedSort *= -1; renderSchedule(); }

  /* ─── Teams ──────────────────────────────────── */

  function renderTeams() {
    var q    = document.getElementById('teams-search').value.trim().toLowerCase();
    var conf = document.getElementById('teams-conf').value;
    var sort = document.getElementById('teams-sort').value;
    var ts   = TEAMS.filter(function (t) {
      if (conf && t.conf !== conf) return false;
      if (q && t.name.toLowerCase().indexOf(q) === -1) return false;
      return true;
    });
    ts = Utils.sortTeams(ts, sort);
    var el = document.getElementById('teams-grid');
    if (!ts.length) { el.innerHTML = emptyState('👥', 'No teams match your search.'); return; }
    el.innerHTML = ts.map(function (tm) {
      return '<article class="team-card" role="button" tabindex="0"' +
        ' aria-label="View ' + esc(tm.name) + ' schedule"' +
        ' onclick="openTeamCalendar(\'' + tm.id + '\')"' +
        ' onkeydown="if(event.key===\'Enter\'||event.key===\' \')openTeamCalendar(\'' + tm.id + '\')">' +
        '<div class="team-flag-lg">' + tm.flag + '</div>' +
        '<div class="team-card-name">' + esc(tm.name) + '</div>' +
        '<div class="team-card-meta">Group ' + tm.group + ' · #' + tm.ranking + ' FIFA</div>' +
        '<span class="conf-badge conf-' + tm.conf + '">' + tm.conf + '</span>' +
        '</article>';
    }).join('');
  }

  /* ─── Groups ─────────────────────────────────── */

  function renderGroups() {
    var q = document.getElementById('groups-search').value.trim().toLowerCase();
    var filtered = GROUPS.filter(function (g) {
      if (!q) return true;
      if (('group ' + g).toLowerCase().indexOf(q) !== -1) return true;
      return TEAMS.some(function (t) {
        return t.group === g && t.name.toLowerCase().indexOf(q) !== -1;
      });
    });
    var el = document.getElementById('groups-grid');
    if (!filtered.length) { el.innerHTML = emptyState('🔍', 'No groups found.'); return; }
    el.innerHTML = filtered.map(function (g) {
      var gteams = Utils.sortTeams(TEAMS.filter(function (t) { return t.group === g; }), 'ranking');
      var rows = gteams.map(function (t, i) {
        return '<tr class="' + (i < 2 ? 'row-advance' : '') + '">' +
          '<td><button class="team-link" onclick="openTeamCalendar(\'' + t.id + '\')">' +
          t.flag + ' ' + esc(t.name) +
          (i < 2 ? ' <span class="advance-tick">✓</span>' : '') +
          '</button></td>' +
          '<td class="col-rank"><span class="rank-chip">#' + t.ranking + '</span></td></tr>';
      }).join('');
      return '<section class="group-card">' +
        '<header class="group-card-hdr"><h3>GROUP ' + g + '</h3></header>' +
        '<table class="group-table"><thead><tr>' +
        '<th scope="col">Team</th><th scope="col" class="col-rank">FIFA #</th>' +
        '</tr></thead><tbody>' + rows + '</tbody></table></section>';
    }).join('');
  }

  /* ─── Bracket ────────────────────────────────── */

  function renderBracket() {
    var rounds = [
      {label: 'Round of 32',   key: 'Round of 32'},
      {label: 'Round of 16',   key: 'Round of 16'},
      {label: 'Quarterfinals', key: 'Quarterfinal'},
      {label: 'Semifinals',    key: 'Semifinal'},
      {label: '3rd Place',     key: '3rd Place'},
      {label: 'Final',         key: 'Final'},
    ];
    document.getElementById('bracket-inner').innerHTML = rounds.map(function (r) {
      var ms = MATCHES.filter(function (m) { return m.stage === r.key; });
      var slots = ms.map(function (m) {
        var ht = teamMap[m.home], at = teamMap[m.away];
        return '<div class="bracket-match">' +
          '<div class="b-team' + (ht ? '' : ' b-tbd') + '">' +
          '<span class="b-flag">' + (ht ? ht.flag : '🏳️') + '</span>' +
          '<span class="b-name">' + esc(ht ? ht.name : m.home) + '</span></div>' +
          '<div class="b-team' + (at ? '' : ' b-tbd') + '">' +
          '<span class="b-flag">' + (at ? at.flag : '🏳️') + '</span>' +
          '<span class="b-name">' + esc(at ? at.name : m.away) + '</span></div></div>';
      }).join('');
      return '<div class="bracket-round"><div class="bracket-round-hdr">' + r.label + '</div>' +
        '<div class="bracket-slots">' + slots + '</div></div>';
    }).join('');
  }

  /* ─── Helpers ────────────────────────────────── */

  function emptyState(icon, msg) {
    return '<div class="empty-state"><span class="empty-icon">' + icon + '</span><p>' + msg + '</p></div>';
  }

  function esc(s) {
    return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  }

  /* ─── Init ───────────────────────────────────── */

  function init() {
    // Build teamMap
    TEAMS.forEach(function (t) { teamMap[t.id] = t; });

    // Populate group dropdown
    var groupSel = document.getElementById('sched-group');
    GROUPS.forEach(function (g) {
      var o = document.createElement('option');
      o.value = g; o.textContent = 'Group ' + g;
      groupSel.appendChild(o);
    });

    // Nav buttons — call renderPage directly, no hash dance
    document.querySelectorAll('.nav-link').forEach(function (btn) {
      btn.addEventListener('click', function () {
        renderPage(btn.dataset.page);
      });
    });

    // Logo link — treat as Home click
    var logo = document.querySelector('.nav-logo');
    if (logo) {
      logo.addEventListener('click', function (e) {
        e.preventDefault();
        renderPage('home');
      });
    }

    // Hero buttons
    var bs = document.getElementById('hero-btn-schedule');
    var bb = document.getElementById('hero-btn-bracket');
    if (bs) bs.addEventListener('click', function () { renderPage('schedule'); });
    if (bb) bb.addEventListener('click', function () { renderPage('bracket'); });

    // Global search
    document.getElementById('global-search').addEventListener('input', function () {
      var q = this.value.trim();
      if (q.length < 2) return;
      var exact = TEAMS.find(function (t) { return t.name.toLowerCase() === q.toLowerCase(); });
      if (exact) {
        goTo('schedule', exact.id);
      } else {
        document.getElementById('sched-search').value = q;
        renderPage('schedule');
      }
    });

    // Schedule filters
    document.getElementById('sched-search').addEventListener('input', renderSchedule);
    document.getElementById('sched-group').addEventListener('change', renderSchedule);
    document.getElementById('sched-stage').addEventListener('change', renderSchedule);
    document.getElementById('sort-date-btn').addEventListener('click', toggleDateSort);

    // Team filters
    document.getElementById('teams-search').addEventListener('input', renderTeams);
    document.getElementById('teams-conf').addEventListener('change', renderTeams);
    document.getElementById('teams-sort').addEventListener('change', renderTeams);

    // Groups search
    document.getElementById('groups-search').addEventListener('input', renderGroups);

    // Start on whatever the hash says (handles refresh + direct links)
    renderPage(pageFromHash());
  }

  document.addEventListener('DOMContentLoaded', init);

}());